name: Build Windows VST3
on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25.x'

      - name: Set up Ninja Build
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: '1.11.1'

      - name: Configure CMake Project
        run: cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Build VST3 Plugin
        run: cmake --build build --config Release

      - name: Package VST3 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UpmixRT-Windows-VST3
          path: build/**/*.vst3
