name: Build Windows VST3
on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Configure CMake Project
        run: cmake --preset default

      - name: Build VST3 Plugin
        run: cmake --build build --config Release

      - name: Package VST3 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UpmixRT-Windows-VST3
          path: build/plugin/UpmixRT_artefacts/Release/VST3/
